name: uva-ir0-assignments
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.2
  - jupyterlab=4.2.4
  - numpy=1.26.4
  - altair=5.4.0
  - nltk=3.9.1
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - xgboost=2.1.1
  - gensim=4.3.3
